// Our categories store SF Symbol names (from the icon picker + default seed).
// Map them to lucide-react icons. Anything unmapped falls back to Tag.
// Covers categoryIcons.ts's grouped picker set + the default seeded categories.

import {
  Activity,
  Apple,
  Bandage,
  Banknote,
  Bell,
  Bike,
  Bird,
  BookOpen,
  Bookmark,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Camera,
  Car,
  Carrot,
  Cat,
  Coffee,
  CreditCard,
  Cross,
  Crown,
  DollarSign,
  Dog,
  Droplet,
  Dumbbell,
  Film,
  Fish,
  Flag,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  Headphones,
  Heart,
  House,
  Key,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  Luggage,
  Mail,
  Map,
  Mountain,
  Music,
  Newspaper,
  Package,
  Paintbrush,
  Palette,
  Pencil,
  Percent,
  Phone,
  Pill,
  Plane,
  Popcorn,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Ship,
  Smartphone,
  Sparkles,
  SquareParking,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Tent,
  Ticket,
  TramFront,
  Trash2,
  TrendingUp,
  Trophy,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wine,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

const map: Record<string, LucideIcon> = {
  // Food & Drink
  'cart.fill': ShoppingCart,
  'basket.fill': ShoppingBasket,
  'fork.knife': Utensils,
  'takeoutbag.and.cup.and.straw.fill': UtensilsCrossed,
  'cup.and.saucer.fill': Coffee,
  'wineglass.fill': Wine,
  'birthday.cake.fill': Cake,
  'carrot.fill': Carrot,
  'fish.fill': Fish,

  // Shopping
  'bag.fill': ShoppingBag,
  'creditcard.fill': CreditCard,
  'gift.fill': Gift,
  'tshirt.fill': Shirt,
  'shippingbox.fill': Package,
  'tag.fill': Tag,
  eyeglasses: Glasses,
  scissors: Scissors,

  // Transport
  'car.fill': Car,
  'bus.fill': Bus,
  'tram.fill': TramFront,
  airplane: Plane,
  bicycle: Bike,
  'fuelpump.fill': Fuel,
  'ferry.fill': Ship,
  parkingsign: SquareParking,

  // Home & Bills
  'house.fill': House,
  'bolt.fill': Zap,
  'drop.fill': Droplet,
  'flame.fill': Flame,
  'lightbulb.fill': Lightbulb,
  wifi: Wifi,
  'phone.fill': Phone,
  iphone: Smartphone,
  'trash.fill': Trash2,
  'wrench.and.screwdriver.fill': Wrench,
  'hammer.fill': Hammer,
  'paintbrush.fill': Paintbrush,

  // Health
  'heart.fill': Heart,
  'cross.fill': Cross,
  stethoscope: Stethoscope,
  'pills.fill': Pill,
  'dumbbell.fill': Dumbbell,
  'figure.run': Activity,
  'bandage.fill': Bandage,

  // Entertainment
  'tv.fill': Tv,
  'music.note': Music,
  'gamecontroller.fill': Gamepad2,
  'film.fill': Film,
  'ticket.fill': Ticket,
  headphones: Headphones,
  'guitars.fill': Guitar,
  'popcorn.fill': Popcorn,
  'camera.fill': Camera,
  'paintpalette.fill': Palette,

  // Work & Study
  'book.fill': BookOpen,
  'graduationcap.fill': GraduationCap,
  pencil: Pencil,
  'briefcase.fill': Briefcase,
  laptopcomputer: Laptop,
  'building.2.fill': Building2,
  'newspaper.fill': Newspaper,
  'envelope.fill': Mail,

  // Money
  'dollarsign.circle.fill': DollarSign,
  'banknote.fill': Banknote,
  'wallet.pass.fill': Wallet,
  'building.columns.fill': Landmark,
  'chart.line.uptrend.xyaxis': TrendingUp,
  percent: Percent,

  // Pets & Nature
  'pawprint.fill': Dog,
  'cat.fill': Cat,
  'bird.fill': Bird,
  'leaf.fill': Leaf,

  // Travel
  'suitcase.fill': Luggage,
  'map.fill': Map,
  globe: Globe,
  'mountain.2.fill': Mountain,
  'tent.fill': Tent,
  'sun.max.fill': Sun,
  'umbrella.fill': Umbrella,

  // Symbols
  'star.fill': Star,
  sparkles: Sparkles,
  'crown.fill': Crown,
  'trophy.fill': Trophy,
  'flag.fill': Flag,
  'bell.fill': Bell,
  'bookmark.fill': Bookmark,
  'key.fill': Key,
  'shield.fill': Shield,
  'person.fill': User,
  'person.2.fill': Users,

  // Legacy aliases (default-seeded categories / older stored values)
  tag: Tag,
  applelogo: Apple,
}

/** lucide icon component for an SF Symbol name; Tag fallback. */
export function iconForSymbol(symbol: string | null | undefined): LucideIcon {
  if (!symbol) return Tag
  return map[symbol] ?? Tag
}
